### ISSUE TITLE
SenseMe fan direction

### ISSUE THREAD

**Issue by zirdum** [mikelawrence/homeassistant-config#1]
Is direction adjustable with this plugin?

I was looking through the scripts and didn't see anything that related to fan direction (nor in TomFaulkner's senseme code).

**Comment by mikelawrence** [comment]
No direction is not currently supported in this component. For some reason I was under the impression theses fans didn't support direction. I'll try it out and see what happens.

**Comment by mikelawrence** [comment]
I've added support for fan direction. Let me know if this works for you. The Left/Right symbols for fan direction in Home Assistant are backwards for my Haiku fan but the underlying labels "forward"/"reverse" are correct. Later I may do a PR for [TomFaulkner/SenseMe](https://github.com/TomFaulkner/SenseMe) library to directly support fan direction.
